name: nexperiment
description: Nexperiment SDK is a Dart package that simplifies the integration of your Flutter/Dart applications with the Nexperiment platform.
version: 1.0.0
repository: https://github.com/Nova-Platforms/nexperiment-flutter-sdk

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
